version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    command:
      - scripts/entrypoint.sh
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - shared_bridge
    volumes:
      - "./:/src"
  postgres:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    env_file:
      - .env
    networks:
      - shared_bridge
    volumes:
      - "pg-data:/var/lib/postgresql/data"
  redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - shared_bridge
    volumes:
      - cache:/data
volumes:
  pg-data:
    driver: local
  cache:
    driver: local
  app-data:
    driver: local
networks:
  shared_bridge:
    driver: bridge